image: docker:stable

services:
  - docker:dind

stages:
  - build
  - test

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - docker info

build:
  stage: build
  script:
    - docker build -t social-nw-tests .

test:
  stage: test
  script:
    - mkdir -p ${HOME}/reports
    - docker run -v ${HOME}/reports:/home/app/TestReports social-nw-tests
